/* Structure of linked list Node
class Node{
    int data;
    Node next;

    Node(int x){
        data = x;
        next = null;
    }
}
*/
class Solution {
    public int helper(Node head){
        if(head==null){
            return 1;
        }
        
        int carry=helper(head.next);
        
        head.data=head.data+carry;
        
        if(head.data<10){
            return 0;
        }
        head.data=0;
        return 1;
    }
    public Node addOne(Node head) {
        int carry=1;
        carry=helper(head);
        
        if(carry==1){
            Node newnode=new Node(1);
            newnode.next=head;
            return newnode;
        }
        return head;
    }
}


/*In this problem, we need to add 1 to a number represented by a singly linked list.

Initially, I considered an iterative approach. Since a singly linked list does not have a prev pointer, we would need to reverse the list, perform the addition, and then reverse it again to restore the original order. This involves multiple traversals of the list.

Instead, we can use recursion to simulate backward traversal without actually reversing the linked list.

The recursive function moves until it reaches the end of the list.

if (head == null) {
    return 1;
}

When we reach null, we return 1, which represents the carry generated by adding one.

Then, while returning from the recursive calls, we add the carry to each node:

int carry = helper(head.next);
head.data = head.data + carry;

If the resulting digit is less than 10, there is no carry to propagate further, so we return 0.

if (head.data < 10) {
    return 0;
}

If the resulting digit is 10, a carry is generated. We set the current digit to 0 and return 1 to the previous node:

head.data = 0;
return 1;

For example:

1 → 2 → 9

The recursion reaches the end and starts processing backward:

9 + 1 = 10

So:

9 → 0, carry = 1

Then:

2 + 1 = 3

No carry remains, so the final result is:

1 → 3 → 0
Handling the final carry

There is one special case:

9 → 9 → 9

After processing all nodes, we get:

0 → 0 → 0

but a carry of 1 is still left.

Therefore, in the main function, if the helper returns 1, we create a new node containing 1 and place it before the original head:

1 → 0 → 0 → 0

If the helper returns 0, there is no remaining carry, so we simply return the original head.

Time Complexity

The recursion visits every node exactly once.

Time Complexity: O(N)

where N is the number of nodes in the linked list.

Although recursion is used, we are not traversing the list multiple times. Each node is processed once during the return phase.

Space Complexity

The recursive function creates one stack frame for each node.

Space Complexity: O(N)

because the recursion depth can be N.

Key Idea

The important observation is:

Since a singly linked list cannot move backward, use recursion to reach the end first and process the nodes while the recursive calls return.

This allows us to add one without reversing the linked list.*/
